_target_: a_scale.sampling.samplers.h_sampler_grid_and_random_isoflop
_partial_: true


#max_iters_per_run: 1000000 # this is to prevent the NN from hanging
neural_net: ${neural_net}
# ------ LM parameters ----#

seq_len: ${seq_len}
vocab_size: ${vocab_size}

# ------
compute_budget: ${hyper_selection.test.C} #3090000 #${select_hyper.compute_budget} # in 1000,000,000; the compute (6*NBK) of test run
# specify the compute budget in multiples of 1000!

time_budget: 100000 #62500

use_grid: True
use_random_isoflops: False

## ------ For IsoFlops -------
n_samples: 100 #100 #100 #100 # number of samples to draw from the isoflop region
## seed for random number generator
rand_key: 6 
isoflop_fracs: 
  - 1


## ------ For Grid ------- 
# spacing of the grid
space_N: 0.5 #0.5 #1 # log base 2
space_B: 0.5 #0.5 #1 # log base 2
space_K: 0.5 #0.5 #1 # log base 2
space_lr: 0.15 #0.5 # log base 10
space_end_lr: 1 #0.5 # log base 10
space_momentum: 1 #0.5 # log base 10 on  (1 - momentum )

## -------- For Grid and IsoFlops -------
max_N: ${hyper_selection.deepseek.max_N}
min_N: ${hyper_selection.deepseek.min_N}

max_B: ${hyper_selection.max_B} #${resource_allocation.B} # 256
min_B: ${hyper_selection.min_B} #${resource_allocation.B} # 16

max_K: ${hyper_selection.deepseek.max_K}
min_K: ${hyper_selection.deepseek.min_K}

min_lr: ${hyper_selection.min_lr} #${resource_allocation.lr} #0.001
max_lr: ${hyper_selection.max_lr} #${resource_allocation.lr} # 0.3

min_end_lr: ${hyper_selection.end_lr}
max_end_lr: ${hyper_selection.end_lr} # these are to be multiplied by the lr

min_momentum: ${hyper_selection.momentum} 
max_momentum: ${hyper_selection.momentum} 

lr_schedule_options: 
  - ${hyper_selection.lr_schedule}
optimizer_options: 
  - ${hyper_selection.optimizer}

step_decay_schedule_options:
  - ${hyper_selection.step_decay_schedule}



