_target_: a_scale.sampling.h_sampler_from_csv
_partial_: true

file_path: ${critical_batch_size_csv}
#inputs/h_samples_critical_batch_size_all_balanced_cosine.csv
#inputs/h_samples_test_nqs_owt_select_lr_sgd.csv #h_samples_critical_batch_size_all_balanced.csv
#inputs/h_samples_critical_batch_size_owt_all_balanced_sgd.csv
#inputs/h_samples_test_nqs_owt_select_lr_adam.csv
#inputs/h_samples_critical_batch_size_for_baseline.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_critical_batch_size_all_balanced.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_critical_batch_size_all_balanced.csv
#inputs/h_samples_critical_batch_size_adamw_small_w_valid_and_test_owt_extended.csv
#inputs/h_samples_critical_batch_size_test_lr_adapt.csv
#inputs/h_samples_critical_batch_size_adamw_small_w_valid_and_test_owt_extended.csv
#inputs/h_samples_critical_batch_size_adamw_small_w_valid_and_test_owt.csv
#inputs/h_samples_critical_batch_size_owt_small_extended.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt.csv
#inputs/h_samples_critical_batch_size_owt_small_extended.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt.csv
#inputs/h_samples_critical_batch_size_owt_small.csv
#inputs/h_samples_critical_batch_size_owt_small_w_valid.csv
#inputs/h_samples_critical_batch_size_adamw_small_w_valid_owt.csv
#inputs/h_samples_critical_batch_size_owt_small_w_valid.csv
#inputs/h_samples_critical_batch_size_owt_small_w_valid_momentum.csv
#inputs/h_samples_critical_batch_size_owt_small_lr.csv
#inputs/h_samples_critical_batch_size_owt_small_w_valid.csv
#inputs/h_samples_critical_batch_size_adamw_small_w_valid_owt.csv
#inputs/h_samples_critical_batch_size_owt_small_w_valid.csv
#inputs/h_samples_critical_batch_size_owt_small.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt.csv
#inputs/h_samples_critical_batch_size_adamw_small.csv
#inputs/h_samples_critical_batch_size_owt_small.csv
#inputs/h_samples_critical_batch_size_adamw_small.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt.csv
#inputs/h_samples_critical_batch_size_owt_small.csv
#inputs/h_samples_critical_batch_size_adamw_small.csv
#inputs/h_samples_critical_batch_size_owt_very_large.csv
#inputs/h_samples_critical_batch_size_adamw_very_large_owt.csv
#inputs/h_samples_critical_batch_size_adamw_small.csv
#inputs/h_samples_critical_batch_size_owt_large.csv
#inputs/h_samples_critical_batch_size_owt_small.csv
#inputs/h_samples_critical_batch_size_adamw_small.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt.csv
#inputs/h_samples_critical_batch_size_adamw_large_owt.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt.csv
#inputs/h_samples_critical_batch_size_owt_small.csv
#inputs/h_samples_critical_batch_size_adamw_small_0.csv
#inputs/h_samples_critical_batch_size_large_2.csv
#h_samples_critical_batch_size_adamw_small.csv     #h_samples_critical_batch_size_lr_2.csv
#h_samples_critical_batch_size_lr_2.csv
#h_samples_critical_batch_size_schedule_tstt.csv
#inputs/h_samples_critical_batch_size_lr_2.csv #_large_N_1.csv #h_samples_critical_batch_size_lr_2.csv #h_samples_critical_batch_size_over_lr.csv #/h_samples_critical_batch_size_over_lr.csv  #inputs/h_samples_critical_batch_size_add_nn_runs_16.csv #h_samples_critical_batch_size_lr_2.csv #h_samples_critical_batch_size_over_lr.csv #h_samples_critical_batch_size_lr_2.csv
seq_len: ${seq_len} # used to calculate total compute used by the samples
