_target_: a_scale.sampling.h_sampler_from_csv
_partial_: true

file_path: ${test_nqs_csv}
#inputs/h_samples_test_nqs_adamw_cosine_valid.csv
#inputs/h_samples_test_nqs_adamw_cosine_timer.csv
#inputs/h_samples_test_nqs_adamw_cosine_valid.csv
#inputs/h_samples_iso_loss_slice_oos_11.csv
#inputs/h_samples_test_nqs_adamw_cosine_valid.csv
#inputs/h_samples_critical_batch_size_all_balanced_cosine_large.csv
#inputs/h_samples_test_nqs_adamw_cosine_valid.csv
#inputs/h_samples_resource_allocation_all_balanced_adamw_cosine_double_test.csv
#inputs/h_samples_critical_batch_size_all_balanced_cosine_small.csv
#inputs/h_samples_test_nqs_owt_valid.csv
#inputs/h_samples_test_nqs_owt_valid_sgd.csv
# inputs/h_samples_test_nqs_owt_select_lr_adam.csv
#inputs/h_samples_test_nqs_owt_valid_sgd.csv
#inputs/h_samples_resource_allocation_owt_very_very_large_on_critical_line_3.csv
#inputs/h_samples_resource_allocation_owt_very_very_large_on_critical_line_2.csv
#inputs/h_samples_test_nqs_owt_valid_sgd.csv
#inputs/h_samples_test_nqs_owt_valid.csv
#inputs/h_samples_critical_batch_size_for_baseline_2.csv
#h_samples_test_nqs_owt_valid.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt_very_very_large_3.csv
#inputs/h_samples_test_nqs_owt_valid.csv
#inputs/h_samples_critical_batch_size_adamw_small_owt_very_very_large_2.csv
#inputs/h_samples_test_nqs_owt_valid_test_double_test.csv
#inputs/h_samples_resource_allocation_owt_add_to_test_adamw_on_critical_line_tst_Sep12.csv
# inputs/h_samples_critical_batch_size_adamw_small_owt_very_very_large.csv
#inputs/h_samples_test_nqs_owt_valid_test_double_test.csv
#inputs/h_samples_test_nqs_isoflop_memory_slice_first_test_14.csv
#inputs/h_samples_test_nqs_isoflop_time_slice_first_test_100_2.csv
#inputs/h_samples_test_nqs_isoflop_memory_slice_first_test_14.csv
#inputs/h_samples_resource_allocation_owt_small_w_valid_and_double_test_adamw_on_critical_line.csv
#inputs/h_samples_test_nqs_isoflop_memory_slice_first_test_16.csv
#inputs/h_samples_test_checkpoint.csv
#inputs/h_samples_test_nqs_isoflop_time_slice_first_test_all.csv
#inputs/h_samples_test_nqs_isoflop_small_square_first_test.csv
#inputs/h_samples_test_nqs_isoflop_time_slice_first_test_all.csv
#inputs/h_samples_test_nqs_isoflop_memory_slice_first_test_11.csv
#inputs/h_samples_resource_allocation_owt_small_w_valid_and_double_test_adamw_on_critical_line.csv
#inputs/h_samples_test_nqs_owt_double_test_adamw.csv
#inputs/h_samples_test_nqs_isoflop_time_slice_first_test_detailed.csv
#inputs/h_samples_test_nqs_owt_double_test_adamw.csv
#inputs/h_samples_test_nqs_isoflop_memory_slice_first_test_2.csv
# inputs/h_samples_test_nqs_isoflop_time_slice_first_test.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_large_square_2.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_crude_2.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_large_square_3.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_square_2.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_crude_2.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_crude_2.csv
#inputs/h_samples_resource_allocation_owt_small_w_valid_and_double_test_adamw_refined_on_critical_line_3.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_mem_extra_fine_2.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_mem_extra_fine_3.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_mem_extra_fine_3.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_mem.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_mem_2.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_mem_fine_3.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_BS_sch.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw_isoflop_slice_all_mem_fine_2.csv
#inputs/h_samples_test_nqs_owt_double_test_adamw.csv
#inputs/h_samples_test_nqs_owt_double_test_adamw_2.csv
#inputs/h_samples_test_nqs_owt_test_adamw_isoflop_slice_5_2.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_test_nqs_owt_test_adamw_isoflop_slice_5_2.csv
#inputs/h_samples_test_nqs_owt_double_test_adamw.csv
#inputs/h_samples_test_nqs_owt_test_adamw_isoflop_slice_4.csv
#inputs/h_samples_test_nqs_owt_double_test_adamw.csv
#inputs/h_samples_test_nqs_owt_test_adamw_isoflop_slice_4.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_test_nqs_owt_double_test_adamw.csv
#inputs/h_samples_test_nqs_owt_validation_adamw_isoflop_slice_4.csv
#inputs/h_samples_critical_batch_size_owt_small_extended.csv
#inputs/h_samples_test_nqs_owt_validation_adamw_isoflop_slice_3.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw.csv
#inputs/h_samples_test_nqs_owt_validation_adamw_isoflop_slice_1.csv
#inputs/h_samples_critical_batch_size_owt_small_extended.csv
#inputs/h_samples_test_nqs_owt_validation_adamw_isoflop_slice_2.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_test_nqs_owt_in_sample_adamw.csv
#inputs/h_samples_test_nqs_owt_in_sample.csv
#inputs/h_samples_test_nqs_owt_validation.csv
#inputs/h_samples_test_nqs_owt_validation_momentum.csv
#inputs/h_samples_test_nqs_owt_isoflop_slice_validation_3.csv
#inputs/h_samples_resource_allocation_owt_small_w_valid_on_critical_line_momentum.csv
#inputs/h_samples_critical_batch_size_owt_small_w_valid_momentum.csv
#inputs/h_samples_test_nqs_owt_validation_momentum.csv
#inputs/h_samples_resource_allocation_owt_small_w_valid_on_critical_line_momentum.csv
#inputs/h_samples_resource_allocation_owt_small_w_valid_on_critical_line_momentum.csv
#inputs/h_samples_test_nqs_owt_validation_adamw.csv
#inputs/h_samples_test_nqs_owt_validation.csv
#inputs/h_samples_test_nqs_owt_in_sample.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_fit_nqs_iso_on_critical_adamw_small_tuning.csv
#inputs/h_samples_test_nqs_owt_in_sample_adamw.csv
#inputs/h_samples_fit_nqs_iso_on_critical_adamw_small_tuning.csv
#inputs/h_samples_resource_allocation_owt_very_large_adamw_on_critical_line.csv
#inputs/h_samples_resource_allocation_owt_very_large_on_critical_line.csv
#inputs/h_samples_fit_nqs_iso_on_critical_adamw_small_tuning.csv
#inputs/h_samples_resource_allocation_owt_very_large_adamw_on_critical_line.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_resource_allocation_owt_very_large_on_critical_line.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_resource_allocation_owt_very_large_adamw_on_critical_line.csv
#inputs/h_samples_critical_batch_size_owt_large.csv
#inputs/h_samples_resource_allocation_owt_very_large_adamw_on_critical_line.csv
#inputs/h_samples_resource_allocation_owt_very_large_on_critical_line.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_resource_allocation_owt_all_adamw_on_critical_line_tst.csv
#inputs/h_samples_test_nqs_adamw_small.csv
#inputs/h_samples_resource_allocation_owt_all_adamw_on_critical_line_tst.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_resource_allocation_owt_all_adamw_on_critical_line_tst.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_fit_nqs_critical_isoflop_3.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_resource_allocation_owt_small_on_critical_line_2.csv
#${samplers.h_sampler_critical_batch_size.file_path}
#inputs/h_samples_fit_nqs_critical_isoflop_3.csv
#h_samples_test_nqs_adamw_small.csv
#h_samples_test_nqs_chunk_10_0.csv # out of [0,1,2]
#inputs/h_samples_test_nqs.csv #_Jul_schedule.csv #_schedule.csv
seq_len: ${seq_len} # used to calculate total compute used by the samples
